"""Shared prompt templates."""
from .system_prompts import (
    SUMMARIZER_ONLY_PROMPT_TEMPLATE,
    FACTS_EXTRACTION_PROMPT_TEMPLATE,
    SUMMARIZER_PROMPT_TEMPLATE,
    REACT_AGENT_SYSTEM_PROMPT,
)

__all__ = [
    "SUMMARIZER_ONLY_PROMPT_TEMPLATE",
    "FACTS_EXTRACTION_PROMPT_TEMPLATE",
    "SUMMARIZER_PROMPT_TEMPLATE",
    "REACT_AGENT_SYSTEM_PROMPT",
]
